### ISSUE TITLE
ghcjs-dom not usable without webkit and webkitgtk on GHCJS (when using stack)

### ISSUE THREAD

**Issue by eallik** [ghcjs/ghcjs-dom#33]
I'm on OS X 10.9.5 and I'd like to use ghcjs-dom with GHCJS (as opposed to GHC and native compilation).

On native, it used to complain:

```setup: The pkg-config package 'webkitgtk-3.0' version >=1.8 is required but it```

now, on GHCJS, it still complains:

```setup: The pkg-config package 'webkit-1.0' version >=1.8 is required but it```

— [the documentation](https://hackage.haskell.org/package/ghcjs-dom) for ghcjs-dom states that it should be usable both with GHC as well as GHCJS (i.e. compling to JavaScript, not running with an in-process spawned Webkit, however I'm failing to see how that could be the case right now.

Is this a bug in the package? is the documentation wrong? am I missing something? am I doing something wrong?

my `build-depends` is:

```
  build-depends:       base >= 4.7 && < 5
                     , ghcjs-dom >=0.2 && <0.3
```

and `stack.yaml` is:

```yaml
flags:
  gtk:
    have-quartz-gtk: true
packages:
- location: '.'
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151029_ghc-7.10.2:
        url: https://github.com/nrolland/ghcjs/releases/download/v0.2.0.20151029/ghcjs-0.2.0.20151029.tar.gz
extra-deps:
 ... autogenerated by stack solver --modify-stack-yaml ...
compiler-check: match-exact
compiler: ghcjs-0.2.0.20151029_ghc-7.10.2
resolver: ghcjs-0.2.0.20151029_ghc-7.10.2
```
